# Generated by Django 5.2.7 on 2026-08-08 12:21

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_alter_landingpagecourse_course'),
        ('parents', '0004_alter_child_image'),
        ('users', '0006_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='اسم الدورة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة الدورة الإلكترونية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('allow_replay', models.BooleanField(default=True, verbose_name='السماح بإعادة المشاهدة')),
                ('access_validity_days', models.PositiveIntegerField(default=365, verbose_name='مدة الصلاحية بالأيام')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, verbose_name='الرابط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_courses', to='users.instructor', verbose_name='المعلم')),
                ('tags', models.ManyToManyField(blank=True, to='courses.tag', verbose_name='الوسوم')),
            ],
            options={
                'verbose_name': 'دورة إلكترونية',
                'verbose_name_plural': 'الدورات الإلكترونية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoLecture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(verbose_name='الترتيب')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('video_url', models.URLField(verbose_name='رابط الفيديو')),
                ('video_platform', models.CharField(choices=[('youtube', 'YouTube Unlisted'), ('vimeo', 'Vimeo Pro'), ('bunny', 'Bunny Stream')], default='youtube', max_length=30, verbose_name='منصة الفيديو')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='المدة بالثواني')),
                ('is_live_stream', models.BooleanField(default=False, verbose_name='بث مباشر')),
                ('live_stream_time', models.DateTimeField(blank=True, null=True, verbose_name='موعد البث المباشر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_lectures', to='courses_online.onlinecourse', verbose_name='الدورة')),
            ],
            options={
                'verbose_name': 'محاضرة فيديو',
                'verbose_name_plural': 'محاضرات الفيديو',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OnlineLectureMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='الملف')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'صورة'), ('doc', 'مستند')], max_length=20, verbose_name='نوع الملف')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses_online.videolecture', verbose_name='المحاضرة')),
            ],
            options={
                'verbose_name': 'مادة تعليمية',
                'verbose_name_plural': 'المواد التعليمية',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VideoWatchProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('watched_seconds', models.PositiveIntegerField(default=0, verbose_name='الثواني المشاهدة')),
                ('total_seconds', models.PositiveIntegerField(default=0, verbose_name='إجمالي الثواني')),
                ('completion_percentage', models.FloatField(default=0.0, verbose_name='نسبة الإكمال')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('last_position_seconds', models.PositiveIntegerField(default=0, verbose_name='آخر موضع')),
                ('watch_count', models.PositiveIntegerField(default=1, verbose_name='عدد المشاهدات')),
                ('last_watched_at', models.DateTimeField(auto_now=True, verbose_name='آخر مشاهدة')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_watch_progress', to='parents.child', verbose_name='الطفل')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_records', to='courses_online.videolecture', verbose_name='المحاضرة')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_watch_progress', to='users.studentuser', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تقدم المشاهدة',
                'verbose_name_plural': 'تقدم المشاهدات',
                'constraints': [models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('lecture', 'student'), name='unique_video_lecture_student_progress'), models.UniqueConstraint(condition=models.Q(('child__isnull', False)), fields=('lecture', 'child'), name='unique_video_lecture_child_progress')],
            },
        ),
    ]
