# Generated by Django 5.2.7 on 2026-08-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolecture',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الفيديو'),
        ),
    ]
