# Generated by Django 5.2.7 on 2026-08-12 15:59

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_online', '0002_alter_videolecture_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinelecturematerial',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PurePosixPath('/app/media')), upload_to='online_materials/', verbose_name='الملف'),
        ),
    ]
