# Generated by Django 5.2.7 on 2026-08-12 16:10

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_online', '0003_alter_onlinelecturematerial_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinelecturematerial',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط خارجي (مثل Google Drive)'),
        ),
        migrations.AlterField(
            model_name='onlinelecturematerial',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PurePosixPath('/app/media')), upload_to='online_materials/', verbose_name='الملف'),
        ),
    ]
