# Generated by Django 5.2.7 on 2026-08-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_online', '0004_onlinelecturematerial_external_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinelecturematerial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='online_materials/', verbose_name='الملف'),
        ),
    ]
