# Generated by Django 5.2.7 on 2026-08-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_online', '0005_scope_online_unique_constraints_to_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videowatchprogress',
            name='watch_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات المكتملة'),
        ),
    ]
