# Generated by Django 5.2.7 on 2026-08-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_online', '0006_alter_videowatchprogress_watch_count'),
        ('parents', '0004_alter_child_image'),
        ('users', '0007_parentonlinecourserating_studentonlinecourserating'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='videowatchprogress',
            constraint=models.CheckConstraint(condition=models.Q(('student__isnull', False), ('child__isnull', False), _connector='OR'), name='video_watch_requires_participant'),
        ),
    ]
