# Generated by Django 6.0.7 on 2026-09-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_online', '0007_videowatchprogress_video_watch_requires_participant'),
        ('parents', '0004_alter_child_image'),
        ('users', '0007_parentonlinecourserating_studentonlinecourserating'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='videowatchprogress',
            name='video_watch_requires_participant',
        ),
        migrations.AddConstraint(
            model_name='videowatchprogress',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('student__isnull', False), ('child__isnull', True)), models.Q(('student__isnull', True), ('child__isnull', False)), _connector='OR'), name='video_watch_requires_participant'),
        ),
    ]
