services:
  redwan-db:
    image: postgres:17
    container_name: redwan-db
    env_file:
      - ./db.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U redwan_courses_center_dev -d redwan_courses_center_dev_db",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redwan-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile_Slim
      target: dev
    env_file:
      - ./backend/.env
    container_name: redwan-backend
    depends_on:
      redwan-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./backend:/app
      - ./backend/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'python3 -c ''import urllib.request; import sys; sys.exit(0) if urllib.request.urlopen("http://localhost:8000/health/").getcode() == 200 else sys.exit(1)''',
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  redwan-frontend:
    stdin_open: true
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile_Slim
      target: dev
    container_name: redwan-frontend
    depends_on:
      redwan-backend:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /home/alyeldeen/.local/share/pnpm/store/v10:/app/.pnpm-store/v10

volumes:
  postgres_data:
  redis_data:
