FROM python:3.14-slim AS bootstrap
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1
WORKDIR /app

FROM bootstrap AS dev
ENV PATH="/app/venv/bin:$PATH"
ENTRYPOINT ["sh", "docker-entrypoint.sh"]

FROM bootstrap AS build
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libffi-dev \
    supervisor \
    && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
COPY . .
RUN chmod +x docker-entrypoint.sh
RUN mkdir -p /etc/supervisor/conf.d && cp supervisord.conf /etc/supervisor/conf.d/supervisord.conf
ENTRYPOINT ["./docker-entrypoint.sh"]