[pytest]
DJANGO_SETTINGS_MODULE = Redwan_courses_center.settings
python_files = test_*.py tests.py *_tests.py
norecursedirs = .venv scripts static media templates .git
addopts = --ignore=scripts --ignore=test_cloudinary.py
django_find_project = true
