[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=info

[program:gunicorn]
command=gunicorn Redwan_courses_center.wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 2 --timeout 120 --graceful-timeout 30 --keep-alive 5
directory=/app
autostart=true
autorestart=true
priority=10
stopwaitsecs=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=DJANGO_SETTINGS_MODULE="Redwan_courses_center.settings"

[program:uvicorn]
command=uvicorn Redwan_courses_center.asgi:application --host 0.0.0.0 --port 8001 --workers 2 --lifespan on --loop uvloop --http httptools
directory=/app
autostart=true
autorestart=true
priority=20
stopwaitsecs=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=DJANGO_SETTINGS_MODULE="Redwan_courses_center.settings"
