# Generated by Django 5.2.7 on 2026-01-27 02:50

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('suspended', 'معلق'), ('completed', 'مكتمل'), ('dropped', 'ملغى'), ('refunded', 'مسترد')], default='active', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dropped_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'إلتحاق',
                'verbose_name_plural': 'الإلتحاقات',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('processing', 'قيد المعالجة'), ('rejected', 'مرفوض'), ('accepted', 'مقبول'), ('expired', 'منتهي الصلاحية')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'نقدًا'), ('card', 'بطاقة'), ('bank_transfer', 'تحويل بنكي'), ('instapay', 'إنستاباي'), ('vodafone_cash', 'فودافون كاش'), ('other', 'طريقة أخرى')], default='cash', max_length=20)),
            ],
            options={
                'verbose_name': 'طلب إلتحاق',
                'verbose_name_plural': 'طلبات الإلتحاق',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('instapay', 'Instapay'), ('vodafone_cash', 'Vodafone Cash'), ('other', 'Other')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('void', 'Void')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'سجل دفع',
                'verbose_name_plural': 'سجلات الدفع',
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'طلب إسترداد',
                'verbose_name_plural': 'طلبات الإسترداد',
            },
        ),
    ]
