# Generated by Django 5.2.7 on 2026-01-27 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollments_payments', '0001_initial'),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='parents.child'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='الدورة'),
        ),
    ]
