# Generated by Django 5.2.7 on 2025-12-20 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('enrollments_payments', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.child'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.studentuser'),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.child'),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.parent'),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_enrollment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.studentuser'),
        ),
        migrations.AddField(
            model_name='payment',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='enrollments_payments.enrollment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.parent'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.studentuser'),
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='enrollments_payments.enrollment'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='requested_by_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests', to='users.parent'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='requested_by_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests', to='users.studentuser'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course'], name='enrollment_course_index'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student'], name='enrollment_student_index'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['child'], name='enrollment_child_index'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('child__isnull', False), ('student__isnull', True)), models.Q(('child__isnull', True), ('student__isnull', False)), _connector='OR'), name='child_or_student_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('course', 'child'), name='unique_course_child_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('course', 'student'), name='unique_course_student_enrollment'),
        ),
        migrations.AddIndex(
            model_name='enrollmentrequest',
            index=models.Index(fields=['course'], name='er_course_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentrequest',
            index=models.Index(fields=['parent'], name='er_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentrequest',
            index=models.Index(fields=['student'], name='er_student_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentrequest',
            index=models.Index(fields=['child'], name='er_child_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('parent__isnull', False), ('child__isnull', False), ('student__isnull', True)), models.Q(('student__isnull', False), ('parent__isnull', True), ('child__isnull', True)), _connector='OR'), name='parent_child_or_student'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0), ('price__isnull', True), _connector='OR'), name='positive_price'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('child__isnull', False)), fields=('course', 'child'), name='unique_course_child_request'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('course', 'student'), name='unique_course_student_request'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['enrollment'], name='pay_enrollment_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payer_parent'], name='pay_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payer_student'], name='pay_student_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='pay_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payer_parent__isnull', False), ('payer_student__isnull', True)), models.Q(('payer_parent__isnull', True), ('payer_student__isnull', False)), _connector='OR'), name='payer_parent_or_student'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('processed_at__isnull', True), ('status__in', ['paid', 'refunded']), _negated=True), name='processed_at_required_for_paid_or_refunded'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['enrollment'], name='refund_enrollment_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['status'], name='refund_status_idx'),
        ),
    ]
