# Generated by Django 5.2.7 on 2026-09-11 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_landingpagecourse_course'),
        ('enrollments_payments', '0004_alter_payment_amount_alter_payment_method_and_more'),
        ('parents', '0004_alter_child_image'),
        ('users', '0006_customuser_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollmentrequest',
            name='positive_price',
        ),
        migrations.AddConstraint(
            model_name='enrollmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0), ('price__isnull', True), _connector='OR'), name='positive_price'),
        ),
    ]
