# Generated by Django 5.2.7 on 2026-08-08 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_landingpagecourse_course'),
        ('courses_online', '0001_initial'),
        ('enrollments_payments', '0004_alter_payment_amount_alter_payment_method_and_more'),
        ('parents', '0004_alter_child_image'),
        ('users', '0006_customuser_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_course_child_enrollment',
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_course_student_enrollment',
        ),
        migrations.RemoveConstraint(
            model_name='enrollmentrequest',
            name='unique_course_child_request',
        ),
        migrations.RemoveConstraint(
            model_name='enrollmentrequest',
            name='unique_course_student_request',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='online_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_enrollments', to='courses_online.onlinecourse', verbose_name='الدورة الإلكترونية'),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='online_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses_online.onlinecourse', verbose_name='الدورة الإلكترونية'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='الدورة'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='الدورة'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('online_course__isnull', True)), models.Q(('course__isnull', True), ('online_course__isnull', False)), _connector='OR'), name='exact_one_course_type_per_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('child__isnull', False), ('course__isnull', False)), fields=('course', 'child'), name='unique_course_child_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False), ('student__isnull', False)), fields=('course', 'student'), name='unique_course_student_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('child__isnull', False), ('online_course__isnull', False)), fields=('online_course', 'child'), name='unique_online_course_child_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('online_course__isnull', False), ('student__isnull', False)), fields=('online_course', 'student'), name='unique_online_course_student_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('child__isnull', False), ('course__isnull', False)), fields=('course', 'child'), name='unique_course_child_request'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False), ('student__isnull', False)), fields=('course', 'student'), name='unique_course_student_request'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('child__isnull', False), ('online_course__isnull', False)), fields=('online_course', 'child'), name='unique_online_course_child_request'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('online_course__isnull', False), ('student__isnull', False)), fields=('online_course', 'student'), name='unique_online_course_student_request'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('online_course__isnull', True)), models.Q(('course__isnull', True), ('online_course__isnull', False)), _connector='OR'), name='exact_one_course_type_per_request'),
        ),
    ]
