# Generated by Django 5.2.7 on 2026-08-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments_payments', '0005_remove_enrollment_unique_course_child_enrollment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدًا'), ('instapay', 'إنستاباي'), ('vodafone_cash', 'فودافون كاش')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('instapay', 'Instapay'), ('vodafone_cash', 'Vodafone Cash')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
    ]
