# Generated by Django 5.2.7 on 2026-09-23 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

LEGACY_PAYMENT_METHODS = ("card", "bank_transfer")


def fold_legacy_payment_methods(apps, schema_editor):
    """Map retired ``card`` / ``bank_transfer`` rows onto the ``other`` catch-all."""
    Payment = apps.get_model("enrollments_payments", "Payment")
    EnrollmentRequest = apps.get_model("enrollments_payments", "EnrollmentRequest")
    Payment.objects.filter(method__in=LEGACY_PAYMENT_METHODS).update(method="other")
    EnrollmentRequest.objects.filter(
        payment_method__in=LEGACY_PAYMENT_METHODS
    ).update(payment_method="other")


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_landingpagecourse_course'),
        ('courses_online', '0001_initial'),
        ('enrollments_payments', '0005_remove_enrollmentrequest_positive_price_and_more'),
        ('parents', '0004_alter_child_image'),
        ('users', '0006_customuser_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_course_child_enrollment',
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_course_student_enrollment',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='online_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_enrollments', to='courses_online.onlinecourse', verbose_name='الدورة الإلكترونية'),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='online_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses_online.onlinecourse', verbose_name='الدورة الإلكترونية'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='الدورة'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='الدورة'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدًا'), ('instapay', 'إنستاباي'), ('vodafone_cash', 'فودافون كاش'), ('other', 'طريقة أخرى')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('instapay', 'Instapay'), ('vodafone_cash', 'Vodafone Cash'), ('other', 'Other')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        # 'card' and 'bank_transfer' are no longer offered; existing rows keep
        # their history under the 'other' bucket. Choices are not enforced by
        # the database, so the reverse is a no-op.
        migrations.RunPython(fold_legacy_payment_methods, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('online_course__isnull', True)), models.Q(('course__isnull', True), ('online_course__isnull', False)), _connector='OR'), name='exact_one_course_type_per_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('child__isnull', False), ('course__isnull', False)), fields=('course', 'child'), name='unique_course_child_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False), ('student__isnull', False)), fields=('course', 'student'), name='unique_course_student_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('child__isnull', False), ('online_course__isnull', False), ('status__in', ['active', 'suspended'])), fields=('online_course', 'child'), name='unique_online_course_child_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('online_course__isnull', False), ('status__in', ['active', 'suspended']), ('student__isnull', False)), fields=('online_course', 'student'), name='unique_online_course_student_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('child__isnull', False), ('online_course__isnull', False), ('status__in', ['pending', 'processing'])), fields=('online_course', 'child'), name='unique_online_course_child_request'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('online_course__isnull', False), ('status__in', ['pending', 'processing']), ('student__isnull', False)), fields=('online_course', 'student'), name='unique_online_course_student_request'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('online_course__isnull', True)), models.Q(('course__isnull', True), ('online_course__isnull', False)), _connector='OR'), name='exact_one_course_type_per_request'),
        ),
    ]
