# Generated by Django 5.2.7 on 2026-08-23 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_landingpagecourse_course'),
        ('courses_online', '0005_scope_online_unique_constraints_to_active'),
        ('enrollments_payments', '0006_alter_enrollmentrequest_payment_method_and_more'),
        ('parents', '0004_alter_child_image'),
        ('users', '0007_parentonlinecourserating_studentonlinecourserating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_online_course_child_enrollment',
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_online_course_student_enrollment',
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('child__isnull', False), ('online_course__isnull', False), ('status__in', ['active', 'suspended'])), fields=('online_course', 'child'), name='unique_online_course_child_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('online_course__isnull', False), ('status__in', ['active', 'suspended']), ('student__isnull', False)), fields=('online_course', 'student'), name='unique_online_course_student_enrollment'),
        ),
    ]
