# Generated by Django 5.2.7 on 2026-09-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments_payments', '0005_remove_enrollmentrequest_positive_price_and_more'),
        ('enrollments_payments', '0008_remove_enrollmentrequest_unique_online_course_child_request_and_more'),
    ]

    operations = [
    ]
