# Generated by Django 5.2.7 on 2026-01-27 20:37

import cloudinary.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة الكورس')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('num_lectures', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('for_adults', models.BooleanField(default=True, verbose_name='للبالغين')),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الحد الأدنى للعمر')),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للعمر')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'كورس',
                'verbose_name_plural': 'الكورسات',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')], verbose_name='يوم الأسبوع')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'ميعاد كورس',
                'verbose_name_plural': 'مواعيد الكورسات',
                'ordering': ['course', 'weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scheduled_at', models.DateTimeField()),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_type', models.CharField(choices=[('quiz', 'امتحان صغير'), ('midterm', 'امتحان نصفي'), ('final', 'امتحان نهائي'), ('assignment', 'واجب'), ('other', 'أخرى')], default='other', max_length=16)),
            ],
            options={
                'verbose_name': 'امتحان',
                'verbose_name_plural': 'الامتحانات',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passed', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نتيجة امتحان',
                'verbose_name_plural': 'نتائج الامتحانات',
                'ordering': ['-entered_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='الترتيب في صفحة الهبوط (الأرقام الأعلى تظهر أولاً)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'كورس مميز في الصفحة الرئيسية',
                'verbose_name_plural': 'الكورسات المميزة في الصفحة الرئيسية',
                'ordering': ['-order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('day', models.DateField(verbose_name='تاريخ المحاضرة')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='وقت البدء')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('lecture_number', models.PositiveIntegerField(verbose_name='رقم المحاضرة')),
                ('status', models.CharField(choices=[('scheduled', 'مجدولة'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='scheduled', max_length=10, verbose_name='حالة المحاضرة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_taken', models.BooleanField(default=False, verbose_name='هل تم أخذ الحضور')),
            ],
            options={
                'verbose_name': 'محاضرة',
                'verbose_name_plural': 'المحاضرات',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='اسم الموسم')),
                ('season_type', models.CharField(choices=[('summer_camp', 'معسكر صيفي'), ('school', 'مدرسة'), ('ramadan', 'رمضان'), ('eid', 'عيد'), ('mid_year', 'معسكر منتصف السنة'), ('other', 'أخرى')], max_length=32, verbose_name='نوع الموسم')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=False, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'موسم',
                'verbose_name_plural': 'المواسم',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم الفئة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'فئة كورس/مدرس',
                'verbose_name_plural': 'فئات الكورسات/المدرسين',
                'ordering': ['name'],
            },
        ),
    ]
