# Generated by Django 5.2.7 on 2025-12-20 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course'),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course'),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='users.child'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_exam_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='courses.exam'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='users.studentuser'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.course'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='users.instructor'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['start_date'], name='season_start_date_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['end_date'], name='season_end_date_idx'),
        ),
        migrations.AddField(
            model_name='course',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.season'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.tag'),
        ),
        migrations.AddIndex(
            model_name='courseschedule',
            index=models.Index(fields=['course'], name='course_schedule_course_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['course'], name='exam_course_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['scheduled_at'], name='exam_scheduled_at_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam'], name='exam_result_exam_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student'], name='exam_result_student_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['child'], name='exam_result_child_idx'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='unique_exam_student'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.UniqueConstraint(fields=('exam', 'child'), name='unique_exam_child'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['course'], name='lecture_course_index'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['day'], name='lecture_day_index'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['course', 'lecture_number'], name='lecture_course_lecture_index'),
        ),
        migrations.AddConstraint(
            model_name='lecture',
            constraint=models.UniqueConstraint(fields=('course', 'lecture_number'), name='unique_course_lecture'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor'], name='course_instructor_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['season'], name='course_season_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['start_date'], name='course_start_date_idx'),
        ),
    ]
