# Generated by Django 5.2.7 on 2026-01-27 16:26
# NOTE: LandingPageCourse is already created in 0001_initial.
# This migration adds the missing course FK and index.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        # Add the course field that was missing from 0001_initial
        migrations.AddField(
            model_name='landingpagecourse',
            name='course',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='landing_page_feature',
                to='courses.course',
                verbose_name='الكورس',
                null=True,  # Allow null temporarily for existing data
            ),
        ),
        # Add the index
        migrations.AddIndex(
            model_name='landingpagecourse',
            index=models.Index(
                fields=['-order', '-created_at'], name='landing_course_order_idx'),
        ),
    ]
