# Generated by Django 5.2.7 on 2026-01-27 16:26
# NOTE: LandingPageCourse is already created in 0001_initial, this migration is a no-op.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        # LandingPageCourse model already created in 0001_initial
        # This migration was kept to maintain migration history integrity
    ]
