# Generated by Django 5.2.7 on 2026-02-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_landingpagecourse'),
        ('users', '0003_alter_studentuser_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_accepted',
            field=models.BooleanField(default=True, verbose_name='هل تم قبول المحاضرة'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='status',
            field=models.CharField(choices=[('scheduled', 'مجدولة'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة'), ('additional', 'اضافية')], default='scheduled', max_length=10, verbose_name='حالة المحاضرة'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['course', 'is_accepted'], name='lecture_course_accepted_index'),
        ),
    ]
