# Generated by Django 5.2.7 on 2026-02-05 19:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_landingpagecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecourse',
            name='course',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='landing_page_feature', to='courses.course', verbose_name='الكورس'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='landingpagecourse',
            index=models.Index(fields=['-order', '-created_at'], name='landing_course_order_idx'),
        ),
    ]
