# Generated by Django 5.2.7 on 2026-02-10
# This migration makes the course field non-nullable

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lecture_is_accepted_alter_lecture_status_and_more'),
    ]

    operations = [
        # Make the course field non-nullable
        # Since it's a OneToOneField, any rows with NULL course should be deleted first
        migrations.RunSQL(
            sql="DELETE FROM courses_landingpagecourse WHERE course_id IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='landingpagecourse',
            name='course',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='landing_page_feature',
                to='courses.course',
                verbose_name='الكورس',
            ),
        ),
    ]
