# Generated by Django 5.2.7 on 2026-01-27 02:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCronLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'سجل إنشاء مهام حضور',
                'verbose_name_plural': 'سجلات مهام إنشاء الحضور الأوتوماتيكية',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'جهاز حضور',
                'verbose_name_plural': 'أجهزة الحضور',
            },
        ),
        migrations.CreateModel(
            name='LectureAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=None, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='التقييم')),
                ('notes', models.TextField(blank=True, null=True)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات حضور الطلاب والأطفال',
            },
        ),
        migrations.CreateModel(
            name='SupervisorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')], verbose_name='يوم الأسبوع')),
                ('start_time', models.TimeField(verbose_name='وقت البدء')),
                ('end_time', models.TimeField(verbose_name='وقت الانتهاء')),
                ('grace_period_minutes', models.PositiveIntegerField(default=20, verbose_name='دقائق فترة السماح')),
                ('auto_absent_after_minutes', models.PositiveIntegerField(default=60, verbose_name='دقائق الغياب التلقائي')),
            ],
            options={
                'verbose_name': 'سجل حضور مدرس/مشرف',
                'verbose_name_plural': 'سجلات حضور المدرسين/المشرفين',
            },
        ),
        migrations.CreateModel(
            name='InstructorAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت تسجيل الدخول')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت تسجيل الخروج')),
                ('check_in_method', models.CharField(blank=True, max_length=20, null=True, verbose_name='طريقة تسجيل الدخول')),
                ('status', models.CharField(choices=[('pending', 'منتظر'), ('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('not_started', 'لم يبدأ')], default='not_started', max_length=20, verbose_name='الحالة')),
                ('rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='التقييم')),
                ('notes', models.TextField(blank=True, null=True)),
                ('check_in_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.attendancedevice')),
            ],
            options={
                'verbose_name': 'سجل حضور معلم/مشرف',
                'verbose_name_plural': 'سجلات حضور المعلمين/المشرفين',
            },
        ),
    ]
