# Generated by Django 5.2.7 on 2025-12-20 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureattendance',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_attendances', to='users.child'),
        ),
        migrations.AddField(
            model_name='lectureattendance',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_attendances', to='courses.lecture'),
        ),
        migrations.AddField(
            model_name='lectureattendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_lecture_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lectureattendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_attendances', to='users.studentuser'),
        ),
        migrations.AddField(
            model_name='parentinstructorrating',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_instructor_ratings', to='courses.course'),
        ),
        migrations.AddField(
            model_name='parentinstructorrating',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_ratings', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='parentinstructorrating',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_ratings', to='users.parent'),
        ),
        migrations.AddField(
            model_name='studentinstructorrating',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_instructor_ratings', to='courses.course'),
        ),
        migrations.AddField(
            model_name='studentinstructorrating',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_ratings', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='studentinstructorrating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_ratings', to='users.studentuser'),
        ),
        migrations.AddIndex(
            model_name='lectureattendance',
            index=models.Index(fields=['lecture'], name='attendance_lecture_index'),
        ),
        migrations.AddIndex(
            model_name='lectureattendance',
            index=models.Index(fields=['child'], name='attendance_child_index'),
        ),
        migrations.AddIndex(
            model_name='lectureattendance',
            index=models.Index(fields=['student'], name='attendance_student_index'),
        ),
        migrations.AddConstraint(
            model_name='lectureattendance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('child__isnull', False), ('student__isnull', True)), models.Q(('child__isnull', True), ('student__isnull', False)), _connector='OR'), name='child_or_student'),
        ),
        migrations.AddConstraint(
            model_name='lectureattendance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rating__gte', 1.0), ('rating__lte', 10.0)), ('rating__isnull', True), _connector='OR'), name='lecture_attendance_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='lectureattendance',
            constraint=models.CheckConstraint(condition=models.Q(('present__isnull', True), ('rating__isnull', False), _connector='OR'), name='present_requires_rating'),
        ),
        migrations.AddConstraint(
            model_name='lectureattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('child__isnull', False)), fields=('lecture', 'child'), name='unique_lecture_child_attendance'),
        ),
        migrations.AddConstraint(
            model_name='lectureattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('lecture', 'student'), name='unique_lecture_student_attendance'),
        ),
        migrations.AddIndex(
            model_name='parentinstructorrating',
            index=models.Index(fields=['parent'], name='rating_parent_index'),
        ),
        migrations.AddConstraint(
            model_name='parentinstructorrating',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1.0), ('rating__lte', 10.0)), name='parent_instructor_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='parentinstructorrating',
            constraint=models.UniqueConstraint(fields=('parent', 'instructor'), name='unique_parent_instructor_rating'),
        ),
        migrations.AddIndex(
            model_name='studentinstructorrating',
            index=models.Index(fields=['student'], name='rating_student_index'),
        ),
        migrations.AddConstraint(
            model_name='studentinstructorrating',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1.0), ('rating__lte', 10.0)), name='student_instructor_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='studentinstructorrating',
            constraint=models.UniqueConstraint(fields=('student', 'instructor'), name='unique_student_instructor_rating'),
        ),
    ]
