# Generated by Django 5.2.7 on 2026-01-27 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('courses', '0001_initial'),
        ('parents', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorattendance',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.instructor', verbose_name='المعلم/المشرف'),
        ),
        migrations.AddField(
            model_name='instructorattendance',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_attendances', to='courses.lecture'),
        ),
        migrations.AddField(
            model_name='instructorattendance',
            name='rated_by',
            field=models.ForeignKey(blank=True, help_text='المشرف الذي قام بتقييم هذا المعلم.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_instructor_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructorattendance',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_attendance', to='courses.season', verbose_name='الموسم'),
        ),
        migrations.AddField(
            model_name='lectureattendance',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_attendances', to='parents.child'),
        ),
        migrations.AddField(
            model_name='lectureattendance',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_attendances', to='courses.lecture'),
        ),
        migrations.AddField(
            model_name='lectureattendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_lecture_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lectureattendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_attendances', to='users.studentuser'),
        ),
        migrations.AddField(
            model_name='supervisorschedule',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_supervisor_schedules', to='users.instructor', verbose_name='المعلم/المشرف'),
        ),
        migrations.AddField(
            model_name='instructorattendance',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='يوم جدول زمني مرتبط إذا كان هذا المدرب مشرفًا.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='attendance.supervisorschedule'),
        ),
        migrations.AddIndex(
            model_name='lectureattendance',
            index=models.Index(fields=['lecture'], name='attendance_lecture_index'),
        ),
        migrations.AddIndex(
            model_name='lectureattendance',
            index=models.Index(fields=['child'], name='attendance_child_index'),
        ),
        migrations.AddIndex(
            model_name='lectureattendance',
            index=models.Index(fields=['student'], name='attendance_student_index'),
        ),
        migrations.AddConstraint(
            model_name='lectureattendance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('child__isnull', False), ('student__isnull', True)), models.Q(('child__isnull', True), ('student__isnull', False)), _connector='OR'), name='child_or_student'),
        ),
        migrations.AddConstraint(
            model_name='lectureattendance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rating__gte', 1.0), ('rating__lte', 10.0)), ('rating__isnull', True), _connector='OR'), name='lecture_attendance_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='lectureattendance',
            constraint=models.CheckConstraint(condition=models.Q(('present__isnull', True), ('rating__isnull', False), _connector='OR'), name='present_requires_rating'),
        ),
        migrations.AddConstraint(
            model_name='lectureattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('child__isnull', False)), fields=('lecture', 'child'), name='unique_lecture_child_attendance'),
        ),
        migrations.AddConstraint(
            model_name='lectureattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('lecture', 'student'), name='unique_lecture_student_attendance'),
        ),
        migrations.AlterUniqueTogether(
            name='supervisorschedule',
            unique_together={('instructor', 'day_of_week')},
        ),
        migrations.AddIndex(
            model_name='instructorattendance',
            index=models.Index(fields=['instructor', 'date'], name='attendance__instruc_3080b1_idx'),
        ),
        migrations.AddIndex(
            model_name='instructorattendance',
            index=models.Index(fields=['season'], name='attendance__season__6b02f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='instructorattendance',
            unique_together={('instructor', 'date')},
        ),
    ]
