# Generated by Django 5.2.7 on 2026-01-27 16:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('courses', '0003_landingpagecourse'),
        ('users', '0002_landingpageinstructor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorattendance',
            name='rated_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ ووقت إضافة/تحديث التقييم', null=True, verbose_name='وقت التقييم'),
        ),
        migrations.AlterField(
            model_name='instructorattendance',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات عامة'),
        ),
        migrations.AlterField(
            model_name='instructorattendance',
            name='rated_by',
            field=models.ForeignKey(blank=True, help_text='المشرف/الأدمن الذي قام بتقييم هذا المعلم.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_instructor_ratings', to=settings.AUTH_USER_MODEL, verbose_name='تم التقييم بواسطة'),
        ),
        migrations.AlterField(
            model_name='instructorattendance',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='null للغائب، 0 للحاضر بدون تقييم، 1-10 للتقييم الفعلي', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='التقييم (1.00 - 10.00)'),
        ),
        migrations.AddIndex(
            model_name='instructorattendance',
            index=models.Index(fields=['rated_by'], name='attendance__rated_b_42fc8f_idx'),
        ),
    ]
