# Generated by Django 5.2.7 on 2026-02-05 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_instructorattendance_rated_at_and_more'),
        ('courses', '0003_landingpagecourse'),
        ('users', '0004_instructor_fingerprint_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instructorattendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='instructorattendance',
            name='attendance_type',
            field=models.CharField(choices=[('lecture', 'محاضرة'), ('supervision', 'إشراف')], default='lecture', max_length=20, verbose_name='نوع الحضور'),
        ),
        migrations.AddField(
            model_name='instructorattendance',
            name='check_out_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_outs', to='attendance.attendancedevice', verbose_name='جهاز تسجيل الخروج'),
        ),
        migrations.AddField(
            model_name='instructorattendance',
            name='check_out_method',
            field=models.CharField(blank=True, choices=[('fingerprint', 'بصمة الإصبع'), ('rfid', 'بطاقة RFID'), ('manual', 'يدوي بواسطة المشرف'), ('qr_code', 'رمز QR')], max_length=20, null=True, verbose_name='طريقة تسجيل الخروج'),
        ),
        migrations.AlterField(
            model_name='instructorattendance',
            name='check_in_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins', to='attendance.attendancedevice', verbose_name='جهاز تسجيل الدخول'),
        ),
        migrations.AlterField(
            model_name='instructorattendance',
            name='check_in_method',
            field=models.CharField(blank=True, choices=[('fingerprint', 'بصمة الإصبع'), ('rfid', 'بطاقة RFID'), ('manual', 'يدوي بواسطة المشرف'), ('qr_code', 'رمز QR')], max_length=20, null=True, verbose_name='طريقة تسجيل الدخول'),
        ),
        migrations.AddIndex(
            model_name='instructorattendance',
            index=models.Index(fields=['attendance_type'], name='attendance__attenda_b37fab_idx'),
        ),
        migrations.AddIndex(
            model_name='instructorattendance',
            index=models.Index(fields=['status', 'date'], name='attendance__status_95dace_idx'),
        ),
        migrations.AddConstraint(
            model_name='instructorattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('lecture__isnull', False)), fields=('instructor', 'lecture'), name='unique_instructor_lecture_attendance'),
        ),
        migrations.AddConstraint(
            model_name='instructorattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule__isnull', False)), fields=('instructor', 'schedule', 'date'), name='unique_instructor_schedule_date_attendance'),
        ),
    ]
