# Generated by Django 5.2.7 on 2026-02-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_instructorattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureattendance',
            name='marked_via',
            field=models.CharField(choices=[('manual', 'يدوي'), ('qr_scan', 'مسح QR')], default='manual', max_length=20, verbose_name='طريقة التسجيل'),
        ),
    ]
