# Generated by Django 5.2.7 on 2026-02-10 02:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_lectureattendance_marked_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureattendance',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='التقييم'),
        ),
    ]
