# Generated by Django 5.2.7 on 2026-02-14 19:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_lectureattendance_rating'),
        ('users', '0005_alter_studentuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerprintScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_time', models.DateTimeField(default=django.utils.timezone.now, help_text='الوقت الفعلي للبصمة (قد يختلف عن وقت المعالجة في حالة الoffline)', verbose_name='وقت البصمة')),
                ('received_time', models.DateTimeField(auto_now_add=True, help_text='وقت وصول البصمة للسيرفر', verbose_name='وقت الاستلام')),
                ('action', models.CharField(choices=[('check_in', 'تسجيل دخول'), ('check_out', 'تسجيل خروج'), ('re_entry', 'إعادة دخول بعد خروج'), ('ignored', 'تم تجاهله (مكرر)'), ('auto_created', 'إنشاء تلقائي للحضور')], help_text='الإجراء الذي تم تحديده بواسطة النظام', max_length=20, verbose_name='الإجراء')),
                ('is_processed', models.BooleanField(default=True, help_text='هل تم تطبيق هذا السجل على سجل الحضور؟', verbose_name='تمت المعالجة')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات إضافية أو سبب التجاهل', null=True, verbose_name='ملاحظات')),
                ('device_sequence', models.IntegerField(blank=True, help_text='رقم التسلسل من الجهاز لتتبع الترتيب', null=True, verbose_name='تسلسل الجهاز')),
                ('attendance', models.ForeignKey(blank=True, help_text='قد يكون فارغاً إذا فشل إنشاء سجل الحضور', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='attendance.instructorattendance', verbose_name='سجل الحضور')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='attendance.attendancedevice', verbose_name='الجهاز')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_scans', to='users.instructor', verbose_name='المعلم/المشرف')),
            ],
            options={
                'verbose_name': 'سجل بصمة',
                'verbose_name_plural': 'سجلات البصمات',
                'ordering': ['-scan_time'],
                'indexes': [models.Index(fields=['instructor', 'scan_time'], name='attendance__instruc_ceeaef_idx'), models.Index(fields=['attendance'], name='attendance__attenda_95def9_idx'), models.Index(fields=['device', 'scan_time'], name='attendance__device__8c6c73_idx'), models.Index(fields=['action'], name='attendance__action_10ac53_idx')],
            },
        ),
    ]
