# Generated by Django 5.2.7 on 2026-03-07 13:18

import attendance.models.websocket_ticket
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_fingerprintscanlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocketTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=attendance.models.websocket_ticket.generate_ticket_token, help_text='Cryptographically secure random token', max_length=64, unique=True, verbose_name='Ticket Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the ticket was created', verbose_name='Created At')),
                ('expires_at', models.DateTimeField(db_index=True, default=attendance.models.websocket_ticket.get_default_expiry, help_text='When the ticket expires (default: 30 seconds from creation)', verbose_name='Expires At')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the ticket was used to establish a connection', null=True, verbose_name='Used At')),
                ('is_used', models.BooleanField(db_index=True, default=False, help_text='Whether this ticket has been used', verbose_name='Is Used')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address that requested the ticket', null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, default='', help_text='Browser/client user agent', max_length=500, verbose_name='User Agent')),
                ('user', models.ForeignKey(help_text='The user this ticket is issued for', on_delete=django.db.models.deletion.CASCADE, related_name='websocket_tickets', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'WebSocket Ticket',
                'verbose_name_plural': 'WebSocket Tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'is_used'], name='attendance__token_2430e6_idx'), models.Index(fields=['user', 'created_at'], name='attendance__user_id_e6d9d8_idx')],
            },
        ),
    ]
