# Generated by Django 6.0.7 on 2026-08-28 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0008_websocket_ticket"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supervisorschedule",
            options={
                "verbose_name": "سجل حضور مدرس/مشرف",
                "verbose_name_plural": "جداول حضور المدرسين/المشرفين",
            },
        ),
    ]
