# Generated by Django 5.2.7 on 2026-08-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_websocket_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supervisorschedule',
            options={'verbose_name': 'سجل حضور مدرس/مشرف', 'verbose_name_plural': 'جداول حضور المدرسين/المشرفين'},
        ),
    ]
