# Generated by Django 5.2.7 on 2026-01-27 02:50

import core.utils.image_utils
import django.db.models.deletion
import parents.models.parent
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='phone number')),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('unique_code', models.CharField(editable=False, max_length=6, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=parents.models.parent.child_upload_path, validators=[core.utils.image_utils.validate_image_size])),
                ('gender', models.CharField(choices=[('boy', 'ولد'), ('girl', 'بنت')], max_length=10, verbose_name='الجنس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'طفل',
                'verbose_name_plural': 'الأطفال',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=parents.models.parent.parent_upload_path, validators=[core.utils.image_utils.validate_image_size])),
            ],
            options={
                'verbose_name': 'ولي أمر',
                'verbose_name_plural': 'أولياء الأمور',
            },
        ),
        migrations.CreateModel(
            name='ParentLinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'طلب ربط ولي أمر بطفل',
                'verbose_name_plural': 'طلبات ربط أولياء أمور ثانويين بأطفال',
            },
        ),
        migrations.CreateModel(
            name='ChildParents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_parents', to='parents.child')),
            ],
            options={
                'verbose_name': 'رابط طفل بولي أمر',
                'verbose_name_plural': 'روابط الأطفال بأولياء الأمور',
            },
        ),
    ]
