# Generated by Django 5.2.7 on 2026-01-27 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='childparents',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_children', to='parents.parent'),
        ),
        migrations.AddField(
            model_name='child',
            name='primary_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_children', to='parents.parent'),
        ),
        migrations.AddField(
            model_name='parentlinkrequest',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_requests', to='parents.child'),
        ),
        migrations.AddField(
            model_name='parentlinkrequest',
            name='primary_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_link_requests', to='parents.parent'),
        ),
        migrations.AddField(
            model_name='parentlinkrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_link_requests', to='parents.parent'),
        ),
        migrations.AlterUniqueTogether(
            name='childparents',
            unique_together={('child', 'parent')},
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['unique_code'], name='parents_chi_unique__f4de0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parentlinkrequest',
            unique_together={('child', 'requester', 'primary_parent')},
        ),
    ]
