# Generated by Django 5.2.7 on 2026-01-30 23:11

import core.utils.image_utils
import django.db.models.deletion
import parents.models.parent
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='dob',
            field=models.DateField(verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='الاسم الأول والثاني'),
        ),
        migrations.AlterField(
            model_name='child',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=parents.models.parent.child_upload_path, validators=[core.utils.image_utils.validate_image_size], verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='الاسم الثالث والرابع'),
        ),
        migrations.AlterField(
            model_name='child',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='child',
            name='primary_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_children', to='parents.parent', verbose_name='الولي الأساسي'),
        ),
        migrations.AlterField(
            model_name='child',
            name='unique_code',
            field=models.CharField(editable=False, max_length=6, unique=True, verbose_name='كود الطفل'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=parents.models.parent.parent_upload_path, validators=[core.utils.image_utils.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
