# Generated by Django 5.2.7 on 2026-02-10 02:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_alter_child_dob_alter_child_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='child_image'),
        ),
    ]
