# Generated by Django 5.2.7 on 2026-01-27 02:50

import cloudinary.models
import core.utils.image_utils
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.models.student
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0001_initial'),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number1', models.CharField(max_length=15, unique=True, verbose_name='رقم الواتس آب')),
                ('phone_number2', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم هاتف بديل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الانضمام')),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق')),
                ('identity_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Government ID / Passport')),
                ('identity_type', models.CharField(choices=[('nid', 'بطاقة وطنية'), ('passport', 'جواز سفر'), ('other', 'أخرى')], default='nid', max_length=20, null=True)),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='النوع')),
                ('address', models.TextField(blank=True, null=True)),
                ('location', models.URLField(blank=True, max_length=512, null=True)),
                ('role', models.CharField(choices=[('student', 'طالب'), ('instructor', 'مدرس'), ('supervisor', 'مشرف'), ('parent', 'ولي أمر'), ('admin', 'مدير')], default='student', max_length=20, verbose_name='الدور')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'جميع المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nid_front', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='nid_front')),
                ('nid_back', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='nid_back')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='instructor_image')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('type', models.CharField(choices=[('supervisor', 'مشرف'), ('normal', 'عادي / خارجي')], default='normal', max_length=20, verbose_name='نوع المعلم')),
                ('tags', models.ManyToManyField(blank=True, related_name='instructors', to='courses.tag', verbose_name='الفئات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'معلم',
                'verbose_name_plural': 'المعلمون',
            },
        ),
        migrations.CreateModel(
            name='ParentCourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='التقييم')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_ratings', to='courses.course', verbose_name='الدورة')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to='parents.parent')),
            ],
            options={
                'verbose_name': 'تقييم ولي أمر لكورس',
                'verbose_name_plural': 'تقييمات أولياء الأمور للكورسات',
            },
        ),
        migrations.CreateModel(
            name='ParentInstructorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='التقييم')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_instructor_ratings', to='courses.course', verbose_name='الدورة')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_ratings', to='users.instructor', verbose_name='المعلم')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_ratings', to='parents.parent')),
            ],
            options={
                'verbose_name': 'تقييم ولي أمر لمدرس',
                'verbose_name_plural': 'تقييمات أولياء الأمور للمدرسين',
            },
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(editable=False, max_length=6, unique=True)),
                ('image', models.ImageField(null=True, upload_to=users.models.student.student_upload_path, validators=[core.utils.image_utils.validate_image_size])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
            },
        ),
        migrations.CreateModel(
            name='StudentInstructorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='التقييم')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_instructor_ratings', to='courses.course', verbose_name='الدورة')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_ratings', to='users.instructor', verbose_name='المعلم')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_ratings', to='users.studentuser')),
            ],
            options={
                'verbose_name': 'تقييم طالب لمدرس',
                'verbose_name_plural': 'تقييمات الطلاب للمدرسين',
            },
        ),
        migrations.CreateModel(
            name='StudentCourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='التقييم')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_ratings', to='courses.course', verbose_name='الدورة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to='users.studentuser')),
            ],
            options={
                'verbose_name': 'تقييم طالب لكورس',
                'verbose_name_plural': 'تقييمات الطلاب للكورسات',
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone_number1'], name='users_custo_phone_n_3b0072_idx'),
        ),
        migrations.AddIndex(
            model_name='parentcourserating',
            index=models.Index(fields=['parent'], name='course_rating_parent_index'),
        ),
        migrations.AddIndex(
            model_name='parentcourserating',
            index=models.Index(fields=['course'], name='parent_course_rating_index'),
        ),
        migrations.AddConstraint(
            model_name='parentcourserating',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1.0), ('rating__lte', 10.0)), name='parent_course_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='parentcourserating',
            constraint=models.UniqueConstraint(fields=('parent', 'course'), name='unique_parent_course_rating'),
        ),
        migrations.AddIndex(
            model_name='parentinstructorrating',
            index=models.Index(fields=['parent'], name='rating_parent_index'),
        ),
        migrations.AddConstraint(
            model_name='parentinstructorrating',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1.0), ('rating__lte', 10.0)), name='parent_instructor_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='parentinstructorrating',
            constraint=models.UniqueConstraint(fields=('parent', 'instructor'), name='unique_parent_instructor_rating'),
        ),
        migrations.AddIndex(
            model_name='studentuser',
            index=models.Index(fields=['unique_code'], name='users_stude_unique__e11322_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinstructorrating',
            index=models.Index(fields=['student'], name='rating_student_index'),
        ),
        migrations.AddConstraint(
            model_name='studentinstructorrating',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1.0), ('rating__lte', 10.0)), name='student_instructor_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='studentinstructorrating',
            constraint=models.UniqueConstraint(fields=('student', 'instructor'), name='unique_student_instructor_rating'),
        ),
        migrations.AddIndex(
            model_name='studentcourserating',
            index=models.Index(fields=['student'], name='course_rating_student_index'),
        ),
        migrations.AddIndex(
            model_name='studentcourserating',
            index=models.Index(fields=['course'], name='student_course_rating_index'),
        ),
        migrations.AddConstraint(
            model_name='studentcourserating',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1.0), ('rating__lte', 10.0)), name='student_course_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='studentcourserating',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course_rating'),
        ),
    ]
