# Generated by Django 5.2.7 on 2025-12-20 07:02

import core.utils.image_utils
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.models.instructor
import users.models.parent
import users.models.student
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='phone number')),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('unique_code', models.CharField(editable=False, max_length=6, unique=True)),
                ('image', models.ImageField(blank=True, default='defaults/user_default.png', null=True, upload_to=users.models.parent.child_upload_path, validators=[core.utils.image_utils.validate_image_size])),
                ('gender', models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Children',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number1', models.CharField(max_length=15, unique=True, verbose_name='WhatsApp phone number')),
                ('phone_number2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Alternative phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('is_verified', models.BooleanField(default=False)),
                ('identity_number', models.CharField(max_length=30, null=True, unique=True, verbose_name='Government ID / Passport')),
                ('identity_type', models.CharField(choices=[('nid', 'National ID'), ('passport', 'Passport'), ('other', 'Other')], default='nid', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('location', models.URLField(blank=True, max_length=512, null=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('supervisor', 'Supervisor'), ('parent', 'Parent'), ('admin', 'Admin')], default='student', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nid_front', models.ImageField(blank=True, null=True, upload_to=users.models.instructor.nid_upload_path, validators=[core.utils.image_utils.validate_image_size])),
                ('nid_back', models.ImageField(blank=True, null=True, upload_to=users.models.instructor.nid_upload_path, validators=[core.utils.image_utils.validate_image_size])),
                ('image', models.ImageField(blank=True, default='defaults/user_default.png', null=True, upload_to=users.models.instructor.instructor_upload_path, validators=[core.utils.image_utils.validate_image_size])),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('supervisor', 'Supervisor'), ('normal', 'Normal / External')], default='normal', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='defaults/user_default.png', null=True, upload_to=users.models.parent.parent_upload_path, validators=[core.utils.image_utils.validate_image_size])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
            },
        ),
        migrations.CreateModel(
            name='ChildParents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_parents', to='users.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_children', to='users.parent')),
            ],
            options={
                'verbose_name': 'Child-Parent Association',
                'verbose_name_plural': 'Child-Parent Associations',
            },
        ),
        migrations.AddField(
            model_name='child',
            name='primary_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_children', to='users.parent'),
        ),
        migrations.CreateModel(
            name='ParentLinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_requests', to='users.child')),
                ('primary_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_link_requests', to='users.parent')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_link_requests', to='users.parent')),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(editable=False, max_length=6, unique=True)),
                ('image', models.ImageField(upload_to=users.models.student.student_upload_path, validators=[core.utils.image_utils.validate_image_size])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='SupervisorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_period_minutes', models.PositiveIntegerField(default=20)),
                ('auto_absent_after_minutes', models.PositiveIntegerField(default=60)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_schedules', to='users.instructor')),
            ],
            options={
                'verbose_name': 'instructor Schedule',
                'verbose_name_plural': 'instructor Schedules',
            },
        ),
        migrations.CreateModel(
            name='InstructorAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('check_in_method', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('not_started', 'Not Started')], default='not_started', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, default=8, help_text='Rating of the instructor for the day (1-10).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('check_in_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.attendancedevice')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.instructor')),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_attendances', to='courses.lecture')),
                ('rated_by', models.ForeignKey(blank=True, help_text='The admin who rated or updated this attendance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_instructor_ratings', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_attendance', to='courses.season')),
                ('schedule', models.ForeignKey(blank=True, help_text='Linked schedule if this instructor is a supervisor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='users.supervisorschedule')),
            ],
            options={
                'verbose_name': 'Instructor Attendance',
                'verbose_name_plural': 'Instructor Attendance Records',
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone_number1'], name='users_custo_phone_n_3b0072_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='childparents',
            unique_together={('child', 'parent')},
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['unique_code'], name='users_child_unique__924e1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parentlinkrequest',
            unique_together={('child', 'requester', 'primary_parent')},
        ),
        migrations.AddIndex(
            model_name='studentuser',
            index=models.Index(fields=['unique_code'], name='users_stude_unique__e11322_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supervisorschedule',
            unique_together={('instructor', 'day_of_week')},
        ),
        migrations.AddIndex(
            model_name='instructorattendance',
            index=models.Index(fields=['instructor', 'date'], name='users_instr_instruc_04a746_idx'),
        ),
        migrations.AddIndex(
            model_name='instructorattendance',
            index=models.Index(fields=['season'], name='users_instr_season__de7539_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='instructorattendance',
            unique_together={('instructor', 'date')},
        ),
    ]
