# Generated by Django 5.2.7 on 2026-01-27 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='الترتيب في صفحة الهبوط (الأرقام الأعلى تظهر أولاً)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('instructor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landing_page_feature', to='users.instructor', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'معلم مميز في الصفحة الرئيسية',
                'verbose_name_plural': 'المعلمون المميزون في الصفحة الرئيسية',
                'ordering': ['-order', '-created_at'],
                'indexes': [models.Index(fields=['-order', '-created_at'], name='landing_instructor_order_idx')],
            },
        ),
    ]
