# Generated by Django 5.2.7 on 2026-01-30 23:11

import core.utils.image_utils
import django.db.models.deletion
import users.models.student
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_landingpageinstructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.student.student_upload_path, validators=[core.utils.image_utils.validate_image_size], verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='unique_code',
            field=models.CharField(editable=False, max_length=6, unique=True, verbose_name='كود الطالب'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
