# Generated by Django 5.2.7 on 2026-02-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_studentuser_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='fingerprint_id',
            field=models.CharField(blank=True, help_text='المعرف الفريد المستخدم من جهاز البصمة لتحديد هذا المعلم', max_length=100, null=True, unique=True, verbose_name='معرف البصمة'),
        ),
    ]
