# Generated by Django 5.2.7 on 2026-02-10 02:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_instructor_fingerprint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='student_image'),
        ),
    ]
