# Generated by Django 5.2.7 on 2026-08-12 15:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_online', '0002_alter_videolecture_video_url'),
        ('parents', '0004_alter_child_image'),
        ('users', '0006_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentOnlineCourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='التقييم')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_ratings', to='courses_online.onlinecourse', verbose_name='الدورة')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_course_ratings', to='parents.parent')),
            ],
            options={
                'verbose_name': 'تقييم ولي أمر لكورس أونلاين',
                'verbose_name_plural': 'تقييمات أولياء الأمور للكورسات الأونلاين',
                'indexes': [models.Index(fields=['parent'], name='online_rating_parent_index'), models.Index(fields=['course'], name='parent_online_rating_index')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1.0), ('rating__lte', 10.0)), name='parent_online_course_rating_range'), models.UniqueConstraint(fields=('parent', 'course'), name='unique_parent_online_course_rating')],
            },
        ),
        migrations.CreateModel(
            name='StudentOnlineCourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='التقييم')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_ratings', to='courses_online.onlinecourse', verbose_name='الدورة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_course_ratings', to='users.studentuser')),
            ],
            options={
                'verbose_name': 'تقييم طالب لكورس أونلاين',
                'verbose_name_plural': 'تقييمات الطلاب للكورسات الأونلاين',
                'indexes': [models.Index(fields=['student'], name='online_rating_student_index'), models.Index(fields=['course'], name='student_online_rating_index')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1.0), ('rating__lte', 10.0)), name='student_online_course_rating_range'), models.UniqueConstraint(fields=('student', 'course'), name='unique_student_online_course_rating')],
            },
        ),
    ]
